### PR TITLE
[DM-33257] Add Confluent schema registry to Sasquatch Helm chart

### PR DESCRIPTION
**Pull request by afausti**
- Use the schema-registry-operator to add Confluent schema registry to Sasquatch Helm chart
- Deploy the strimzi entity operator to create the schema registry topic and user
- Enable authentication and authorization
- Ingress configuration for the schema registry will be added in another PR

### CODE REVIEW

**Review by jonathansick — COMMENTED** [review]
@afausti This looks good and the topic and user configurations look right.

I'm a bit unsure about the architecture: should this sasquatch chart also be including the strimzi-registry-operator as a subchart? At the moment, strimzi-registry-operator only watches a single namespace, and that namespace is defined in the strimzi-registry-operator's chart: https://github.com/lsst-sqre/charts/blob/cc9530c34a59f5dbafb9419c32328ec0d2da09a2/charts/strimzi-registry-operator/values.yaml#L9

Also note the configuration for the Kafka cluster name: https://github.com/lsst-sqre/charts/blob/cc9530c34a59f5dbafb9419c32328ec0d2da09a2/charts/strimzi-registry-operator/values.yaml#L7

This leads me to think that, at least for now, strimzi-registry-operator might be better as an explicit sub-chart so that the sasquash deployment's namespace and cluster name can be coordinated with the strimzi-registry-operator set up?

The way to get around this will be to make strimzi-registry-operator work with multiple namespaces and multiple Kafka clusters. I'm looking back into modernizing strimzi-registry-operator to work better for non-Roundtable usage, but I'm not sure when it'll be done.

**Comment by afausti** [comment]
@jonathansick that's an excellent point, thanks for bringing this up. I think it is fine to add the `strimzi-registry-operator` as a subchart to sasquatch, I'll try that.

**Comment by afausti** [comment]
@jonathansick I tried using the `strimzi-registry-operator` chart as a dependency of sasquatch to avoid duplicating the chart. However, [this line](https://github.com/lsst-sqre/charts/blob/master/charts/strimzi-registry-operator/templates/rbac.yaml#L54) expands to `namespace: default` instead of `namespace: sasquatch`. One option would be to add `operatorNamespace` in the `values.yaml` and use that in the RBAC. The default value could `operatorNamespace: strimzi-registry-operator` so that chart still works if deployed on its own namespace, but I was wondering if there's a better way to do it.

**Comment by jonathansick** [comment]
That seems reasonable. Maybe check in with the chart for the Alerts system and @spenczar to make sure that's compatible with how the strimzi-registry-operator chart is being used there.

**Comment by spenczar** [comment]
That works for me, yep.

**Comment by afausti** [comment]
Just tried the new chart in my minikube environment and it's working fine, thank you all for the help.

```[2022-01-20 22:29:20,222] INFO Server started, listening for requests... (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain)```

**Pull request merged**
