### PR TITLE
DM-33534: Add production-tools to data-int.

### PR DESCRIPTION
**Pull request by ctslater**

### CODE REVIEW

**Comment by afausti** [comment]
Hey @ctslater just checking about the state of this PR, is this something you would like to merge? or should we close it?

**Comment by ctslater** [comment]
Hi @afausti, yeah it's still on my radar to finish this up. But I guess I should now put this directly into phalanx, so I'll close this one once I've moved the chart into the phalanx PR.

**Comment by afausti** [comment]
Perfect, thank you!

**Comment by ctslater** [comment]
Superseded by lsst-sqre/phalanx#1193.

**Pull request closed without merging**
